/* autogenerated by Processing revision 1310 on 2026-01-31 */
import processing.core.*;
import processing.data.*;
import processing.event.*;
import processing.opengl.*;

import java.util.HashMap;
import java.util.ArrayList;
import java.io.File;
import java.io.BufferedReader;
import java.io.PrintWriter;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.IOException;

public class AF22059_TITAN_SLAYER_3D extends PApplet {

// ==========================================
// ゲームバランス設定
// ==========================================
// ランク判定の基準：倒した数
int RANK_S_THRESHOLD = 10; // Sランク: 10体以上
int RANK_A_THRESHOLD = 7;  // Aランク: 7体以上
int RANK_B_THRESHOLD = 4;  // Bランク: 4体以上
int RANK_C_THRESHOLD = 1;  // Cランク: 1体以上

// プレイヤーと巨人のパラメータ
float GAME_DURATION = 60.0f; // 制限時間（秒）
float WALK_SPEED = 8.0f;     // WASD移動の速さ
float ANCHOR_SPEED = 45.0f;  // アンカー巻き取り時の接近速度
float LOOK_SPEED = 0.04f;    // 視点移動（E/Q）の速さ

float TITAN_HEIGHT = 2000;  // 巨人の身長
float TITAN_WIDTH = 400;    // 巨人の横幅
float MAX_HP = 25000;       // 巨人のHP
float MAX_DISTANCE = 4000;  // 後ろに下がれる最大距離
float ATTACK_RANGE = 600;   // ブレードが届く距離
float CRASH_DISTANCE = 200; // これ以上近づくと激突する距離

// ==========================================
// グローバル変数
// ==========================================
// ゲームの状態管理用定数
int STATE_TITLE = 0;    // タイトル
int STATE_TUTORIAL = 1; // チュートリアル
int STATE_GAME = 2;     // ゲーム本編
int STATE_RESULT = 3;   // リザルト
int currentState = STATE_TITLE; // 現在の状態

// チュートリアル進行管理
int tutorialStep = 0;
int tutorialTimer = 0; // メッセージ送り待ち時間用

// フォントデータ
PFont jpFont;

// ゲームプレイ中の変動値
float timeLeft;           // 残り時間
int killCount = 0;        // 討伐数
float enemyHP = MAX_HP;   // 現在の敵HP

// プレイヤーの位置・カメラ情報
float playerDist = 2000;  // 巨人からの距離
float playerAngle = 0;    // 巨人の周りのどの角度にいるか（0～TWO_PI）
float playerY = 200;      // プレイヤーの高さ（地面=500, 画面下が正方向）
float cameraPitch = 0;    // カメラの上下角度

// 巨人の情報
float titanX = 0, titanZ = 0; // 巨人の位置
float titanRot = 0;           // 巨人の向き
float titanMoveTimer = 0;     // AIの行動切り替えタイマー

// 判定用変数（うなじが画面のどこにあるか）
float napeScreenX = 0;
float napeScreenY = 0;
boolean isNapeVisible = false; // うなじが背後から見えているか

// キー入力フラグ（同時押し対応のため）
boolean keyW, keyA, keyS, keyD, keyE, keyQ;
boolean isDragging = false;     // マウスドラッグ中か
boolean isAttached = false;     // アンカーが刺さっているか
boolean isTargetLocked = false; // ロックオンできているか

// マウス回転・攻撃判定用
int TRAIL_LENGTH = 5; // 軌跡の長さ
float lastMouseAngle = 0; // 前フレームのマウス角度
ArrayList<PVector> mouseTrail = new ArrayList<PVector>(); // マウス位置の履歴

// 画像・3Dオブジェクトデータ
PImage faceTexture, napeTexture;
float[] treeX = new float[50]; // 森の木々の座標
float[] treeZ = new float[50];
float[] treeH = new float[50];

// 画面エフェクト（ダメージ時の赤フラッシュなど）
int flashColor = color(0, 0, 0, 0);

// ==========================================
// 初期化処理
// ==========================================
public void setup() {
  /* size commented out by preprocessor */; // 3Dモードで画面作成
  noStroke(); // 図形の輪郭線なし
  
  // ウィンドウ位置の調整
  surface.setResizable(true);
  surface.setLocation(100, 100);
  
  // 日本語フォントの作成
  jpFont = createFont("SansSerif", 32, true); 
  textFont(jpFont);
  
  // テクスチャと森の生成
  createTextures();
  createForest();
}

// ==========================================
// メインループ (1秒間に60回実行)
// ==========================================
public void draw() {
  background(135, 206, 235); // 背景色（空の青）
  
  // 現在のゲーム状態に合わせて描画処理を切り替える
  if (currentState == STATE_TITLE) {
    drawTitle();
  } else if (currentState == STATE_TUTORIAL) {
    playTutorial();
  } else if (currentState == STATE_GAME) {
    playGame();
  } else if (currentState == STATE_RESULT) {
    drawResult();
  }
  
  // フラッシュエフェクト（透明度が0より大きければ画面を覆う四角を描画）
  if (alpha(flashColor) > 0) {
    hint(DISABLE_DEPTH_TEST); // 最前面に描画するための設定
    fill(flashColor);
    rect(0, 0, width, height);
    hint(ENABLE_DEPTH_TEST);
    // 徐々に透明にする（フェードアウト）
    flashColor = color(red(flashColor), green(flashColor), blue(flashColor), alpha(flashColor) - 10);
  }
}

// ==========================================
// 1. タイトル画面の描画
// ==========================================
public void drawTitle() {
  hint(DISABLE_DEPTH_TEST); // 2D描画モード（3Dの奥行きを無視）
  background(20);
  textAlign(CENTER, CENTER);
  
  fill(255);
  textSize(50);
  text("立体機動訓練シミュレーター", width/2, height/2 - 80);
  textSize(20);
  fill(200);
  // 操作説明テキスト
  text("WASD:移動  Q:見上げ E:見下げ", width/2, height/2 + 20);
  text("左クリック+回転：アンカー＆接近", width/2, height/2 + 50);
  text("右クリック+ドラッグ：攻撃", width/2, height/2 + 80);
  
  fill(255, 255, 0);
  textSize(24);
  text("[スペースキーで訓練開始]", width/2, height/2 + 150);
  
  // スペースキーでゲーム開始
  if (keyPressed && key == ' ') {
    resetGameParams();
    currentState = STATE_TUTORIAL;
    tutorialStep = 0;
    tutorialTimer = 0;
    playerDist = 2000;
    playerAngle = 0;
    playerY = 200; 
    cameraPitch = 0;
    titanRot = PI; // 最初は巨人を後ろ向きにする
  }
  hint(ENABLE_DEPTH_TEST);
}

// ==========================================
// 2. チュートリアル処理
// ==========================================
public void playTutorial() {
  updatePlayer();     // プレイヤー移動計算
  drawWorld();        // 3D世界描画
  checkTargeting();   // ロックオン判定
  drawReticle();      // 照準描画
  
  String message = "";
  
  // 進行度（step）に応じた処理
  switch(tutorialStep) {
    case 0:
      message = "教官「移動訓練だ。『A』『D』で背後に回り込め。\n『Q』キーで見上げ、赤い弱点を画面中央に捉えろ！」";
      // ロックオン成功したら次へ
      if (isTargetLocked) tutorialStep = 1;
      break;
      
    case 1:
      message = "教官「よし、捉えたな！照準が赤くなったはずだ。\n中央の円の中にマウスを入れて\n『左クリック』でアンカーを撃て！」";
      // アンカーが刺さったら次へ
      if (isAttached) tutorialStep = 2;
      break;
      
    case 2:
      message = "教官「繋がった！左クリックを押したまま\nマウスを『グルグル』回して急上昇・接近しろ！」";
      if (mousePressed && mouseButton == LEFT && isAttached) detectRotationAndMove();
      // 十分近づき、かつ高さも上がったら次へ
      if (playerDist < ATTACK_RANGE && playerY < -TITAN_HEIGHT/3) tutorialStep = 3;
      break;
      
    case 3:
      message = "教官「今だ！『右クリック』を押したまま\nマウスを激しくドラッグして肉を削ぎ落とせ！」";
      if (mousePressed && mouseButton == RIGHT) updateBladeTrail();
      // 巨人を倒したら次へ
      if (killCount > 0) {
        tutorialStep = 4;
        tutorialTimer = 0;
      }
      break;
      
    case 4:
      // 誤操作防止のウェイト処理
      tutorialTimer++;
      message = "教官「完璧だ。これで訓練は終了する。\nいよいよ実戦だ…心臓を捧げよ！」\n\n[クリックして試験開始]";
      
      // 1秒待ってからクリックを受け付ける
      if (tutorialTimer > 60 && mousePressed) {
        resetGameParams();
        currentState = STATE_GAME;
      }
      break;
  }
  // 画面下にメッセージを表示
  drawMessageWindow(message);
}

// ==========================================
// 3. ゲーム本編の処理
// ==========================================
public void playGame() {
  // 制限時間の減少
  timeLeft -= 1.0f / 60.0f;
  if (timeLeft <= 0) {
    timeLeft = 0;
    currentState = STATE_RESULT; // 時間切れでリザルトへ
  }

  // 各要素の更新と描画
  updateTitanAI();    // 敵の移動
  updatePlayer();     // プレイヤーの移動
  drawWorld();        // 3D描画
  checkTargeting();   // 照準計算
  drawReticle();      // 照準描画
  drawHUD();          // 情報表示

  // マウス入力によるアクション
  if (mousePressed) {
    if (mouseButton == LEFT) {
      if (!isAttached) {
        // 発射処理は mousePressed関数で管理
      } else {
        // アンカー巻き取り（グルグル）
        detectRotationAndMove(); 
      }
    } 
    else if (mouseButton == RIGHT) {
      // ブレード攻撃（ドラッグ）
      if (isAttached && playerDist < ATTACK_RANGE) { 
        updateBladeTrail();
      }
    }
  } else {
    // クリックしていない時はリセット
    isDragging = false;
    mouseTrail.clear();
  }
  
  // 激突判定（近づきすぎペナルティ）
  if (playerDist < CRASH_DISTANCE) {
    applyPenalty();
  }
}

// ==========================================
// マウス入力イベント
// ==========================================
public void mousePressed() {
  // ゲーム中、またはチュートリアル発射ステップの時のみ有効
  if (currentState == STATE_GAME || (currentState == STATE_TUTORIAL && tutorialStep == 1)) {
    if (mouseButton == LEFT && !isAttached) {
      // ロックオン中 かつ 画面中央付近をクリックした時だけ発射
      if (isTargetLocked && dist(mouseX, mouseY, width/2, height/2) < 80) {
        fireAnchor();
      }
    }
  }
}

// ==========================================
// 激突ペナルティ処理
// ==========================================
public void applyPenalty() {
  // 距離を強制的に離す（弾き飛ばされる）
  playerDist = 1000;
  // 時間を減らすペナルティ
  timeLeft -= 3.0f;
  // アンカーを外す
  isAttached = false;
  // 画面を赤くフラッシュさせる
  flashColor = color(255, 0, 0, 150);
}

// ==========================================
// プレイヤーの移動・カメラ制御
// ==========================================
public void updatePlayer() {
  // アンカーが刺さっていない時だけWASD移動可能
  if (!isAttached) {
    if (keyA) playerAngle += 0.03f; // 左旋回
    if (keyD) playerAngle -= 0.03f; // 右旋回
    if (keyW) playerDist -= WALK_SPEED; // 前進
    if (keyS) playerDist += WALK_SPEED; // 後退
    
    // 移動範囲の制限
    if (playerDist < 300) playerDist = 300;
    if (playerDist > MAX_DISTANCE) playerDist = MAX_DISTANCE;
    
    // 重力表現（ジャンプしていても徐々に地面の高さに戻る）
    playerY = lerp(playerY, 200, 0.1f);
  }
  
  // 視点操作（Qで見上げ、Eで見下げ）
  if (keyQ) cameraPitch += LOOK_SPEED; 
  if (keyE) cameraPitch -= LOOK_SPEED; 
  // 首が回りすぎないように角度制限
  cameraPitch = constrain(cameraPitch, -PI/2.1f, PI/6); 
  
  // 角度の正規化（一周回った時の処理）
  if (playerAngle > PI) playerAngle -= TWO_PI;
  if (playerAngle < -PI) playerAngle += TWO_PI;
}

// ==========================================
// 巨人のAI
// ==========================================
public void updateTitanAI() {
  // プレイヤーが張り付いている間は動けない
  if (isAttached) return;
  
  titanMoveTimer++;
  // 一定時間ごとにランダムに動く
  if (titanMoveTimer > 100) {
    titanRot += random(-0.05f, 0.05f); // 回転
    titanX += random(-3, 3); // 移動
    titanZ += random(-3, 3);
    // 移動範囲制限
    titanX = constrain(titanX, -1000, 1000);
    titanZ = constrain(titanZ, -1000, 1000);
    
    if (titanMoveTimer > 150) titanMoveTimer = 0;
  }
}

// ==========================================
// 3D空間の描画処理
// ==========================================
public void drawWorld() {
  pushMatrix();
  // 1. カメラ位置の設定
  translate(width/2, height/2); // 画面中央基準
  rotateX(cameraPitch); // 上下の視点回転
  translate(0, -playerY, -playerDist); // プレイヤー位置分ずらす
  rotateY(playerAngle); // 左右の視点回転
  
  // 2. ワールド座標系（巨人のいる場所）
  pushMatrix();
  translate(titanX, 0, titanZ); // 巨人の位置へ
  rotateY(titanRot); // 巨人の向き
  
  // 3. 巨人の描画（足元を地面に合わせる）
  translate(0, 500 - TITAN_HEIGHT/2, 0);
  drawTallTitan(TITAN_WIDTH, TITAN_HEIGHT);
  popMatrix();
  
  // 4. 背景オブジェクト（地面と森）
  drawGrid();
  drawForest();
  popMatrix();
}

// ==========================================
// 照準・ロックオン判定ロジック
// ==========================================
public void checkTargeting() {
  isTargetLocked = false;
  isNapeVisible = false;
  
  // 1. 背後にいるかどうかの判定（角度計算）
  float totalRot = (playerAngle + titanRot) % TWO_PI;
  if (totalRot < 0) totalRot += TWO_PI;
  float distFromBack = abs(totalRot - PI);
  // PI(180度)に近いほど背面（誤差0.6ラジアン以内ならOK）
  boolean isBehind = (distFromBack < 0.6f); 
  isNapeVisible = isBehind; 
  
  // 2. 画面上の位置判定（うなじが中央にあるか）
  float d = dist(napeScreenX, napeScreenY, width/2, height/2);
  boolean isInCircle = (d < 80); // 半径80px以内
  
  // 両方の条件を満たせばロックオン
  if (isBehind && isInCircle) {
    isTargetLocked = true;
  }
}

// アンカー発射処理
public void fireAnchor() {
  isAttached = true;
  // 発射エフェクト（黒い線）
  stroke(0); strokeWeight(3);
  line(width/2, height, width/2, height/2); 
  noStroke();
}

// 回転検知＆立体機動移動
public void detectRotationAndMove() {
  float cx = width / 2;
  float cy = height / 2;
  // マウスの現在角度を計算
  float currentAngle = atan2(mouseY - cy, mouseX - cx);
  
  // ワイヤー描画
  stroke(50); strokeWeight(3);
  line(width/2 - 150, height, width/2, height/2); 
  line(width/2 + 150, height, width/2, height/2); 
  noStroke();
  
  if (!isDragging) {
    lastMouseAngle = currentAngle;
    isDragging = true;
  } else {
    // 角度の変化量を計算
    float delta = currentAngle - lastMouseAngle;
    // 角度の切れ目（-PIとPI）を跨いだ時の補正
    if (delta > PI) delta -= TWO_PI;
    if (delta < -PI) delta += TWO_PI;
    
    // 回転量（絶対値）
    float rotationInput = abs(delta);
    
    // 一定以上回していれば移動
    if (rotationInput > 0.1f) {
      playerDist -= rotationInput * ANCHOR_SPEED; // 接近
      if (playerDist < 100) playerDist = 100;
      
      // 高さ制御：うなじの高さへ向かって上昇する
      float targetH = -TITAN_HEIGHT + 500; 
      playerY = lerp(playerY, targetH, 0.05f * rotationInput); 
      // カメラ角度も自動で少し正面に戻す
      cameraPitch = lerp(cameraPitch, 0, 0.02f);
    }
    lastMouseAngle = currentAngle;
  }
}

// ブレード処理
public void updateBladeTrail() {
  // マウス軌跡を保存
  mouseTrail.add(new PVector(mouseX, mouseY));
  if (mouseTrail.size() > TRAIL_LENGTH) mouseTrail.remove(0);
  
  // 軌跡が十分あれば判定
  if (mouseTrail.size() >= 3) {
    PVector s = mouseTrail.get(0); // 始点
    PVector e = mouseTrail.get(mouseTrail.size() - 1); // 終点
    float d = PVector.dist(s, e); // 移動距離
    
    // マウスが巨人のうなじ座標に近いかチェック
    float distToTitan = dist(mouseX, mouseY, napeScreenX, napeScreenY);    
    // 移動距離に応じてダメージ
    float damage = 0;
    if (distToTitan < 150) {  // (半径150px以内)
       damage = d * 2.5f;
    }
    if (damage > 15) { // 素早く動かさないとダメージが入らない
      enemyHP -= damage;
      // 斬撃エフェクト
      stroke(255, 255, 200); strokeWeight(10);
      line(s.x, s.y, e.x, e.y);
      noStroke();
      
      // 討伐判定
      if (enemyHP <= 0) {
        killCount++;
        flashColor = color(255); // 白フラッシュ
        resetEnemy(); // 次の敵へ
      }
    }
  }
}

// ==========================================
// 描画ヘルパー・UI表示
// ==========================================
public void drawReticle() {
  hint(DISABLE_DEPTH_TEST); // 最前面に描画
  noFill();

  strokeWeight(3);
  
  // 状態によってレティクル（照準線）の色を変える
  if (isAttached) {
    if (playerDist < ATTACK_RANGE) {
      stroke(255, 0, 0); // 攻撃可能距離（赤）
    } else {
      stroke(0, 255, 0); // 接近中（緑）
    }
  } else if (isTargetLocked) {
    stroke(255, 0, 0); // ロックオン（赤）
    fill(255, 0, 0); textAlign(CENTER); textSize(20);
    text("CLICK CENTER!", width/2, height/2 - 90);
    noFill();
  } else {
    stroke(200); // 圏外（白）
  }
  
  ellipse(width/2, height/2, 160, 160); // 中央円
  
  // 敵のHPバー
  if (enemyHP < MAX_HP) {
    noStroke();
    float barW = 400;
    fill(50, 0, 0); rect(width/2 - barW/2, 50, barW, 20); // 背景
    fill(255, 0, 0); rect(width/2 - barW/2, 50, map(enemyHP, 0, MAX_HP, 0, barW), 20); // 現在値
  }
  hint(ENABLE_DEPTH_TEST);
}

// メッセージウィンドウ描画
public void drawMessageWindow(String msg) {
  hint(DISABLE_DEPTH_TEST);
  fill(0, 0, 0, 200);
  stroke(255); strokeWeight(2);
  float boxH = 160;
  rect(50, height - boxH - 20, width - 100, boxH, 10);
  noStroke();
  fill(255); textAlign(LEFT, TOP); textSize(24); textLeading(32); 
  text(msg, 70, height - boxH, width - 140, boxH - 20);
  hint(ENABLE_DEPTH_TEST);
}

// HUD描画
public void drawHUD() {
  hint(DISABLE_DEPTH_TEST);
  fill(0); textAlign(LEFT, TOP); textSize(24);
  text("TIME: " + nf(timeLeft, 2, 1), 20, 20);
  text("KILLS: " + killCount, 20, 50);
  hint(ENABLE_DEPTH_TEST);
}

// リザルト画面描画
public void drawResult() {
  hint(DISABLE_DEPTH_TEST);
  background(0); textAlign(CENTER, CENTER);
  
  fill(255); textSize(40);
  text("MISSION OVER", width/2, height/2 - 60);
  textSize(30);
  text("討伐数: " + killCount + " 体", width/2, height/2 + 20);
  
  // ランク判定
  String r = "D (家畜)"; int c = color(150);
  if (killCount >= RANK_S_THRESHOLD) { r = "S (人類最強)"; c = color(255, 215, 0); }
  else if (killCount >= RANK_A_THRESHOLD) { r = "A (精鋭)"; c = color(255, 100, 100); }
  else if (killCount >= RANK_B_THRESHOLD) { r = "B (調査兵)"; c = color(100, 100, 255); }
  else if (killCount >= RANK_C_THRESHOLD) { r = "C (訓練兵)"; c = color(100, 255, 100); }
  
  fill(c); textSize(50);
  text(r, width/2, height/2 + 100);
  
  fill(255); textSize(20);
  text("[R] RETURN TO TITLE", width/2, height - 50);
  
  // Rキーでタイトルへ戻る
  if (keyPressed && (key == 'r' || key == 'R')) currentState = STATE_TITLE;
  hint(ENABLE_DEPTH_TEST);
}

// ==========================================
// ゲームデータのリセット処理
// ==========================================
public void resetGameParams() {
  timeLeft = GAME_DURATION;
  killCount = 0;
  resetEnemy();
}

public void resetEnemy() {
  enemyHP = MAX_HP;
  playerDist = 2000;
  playerY = 200; 
  isAttached = false;
  titanX = 0; titanZ = 0;
  titanRot = random(TWO_PI); // 向きはランダム
  titanMoveTimer = 0;
  mouseTrail.clear();
}

// ==========================================
// 3Dオブジェクト生成・描画関数
// ==========================================

// 巨人の描画
public void drawTallTitan(float w, float h) {
  float hw = w / 2;
  float hh = h / 2;
  
  // うなじ（赤い部分）を描画
  beginShape(QUADS); texture(napeTexture);
  vertex(hw, -hh, -hw, 0, 0);           
  vertex(-hw, -hh, -hw, 200, 0);        
  vertex(-hw, -hh + 300, -hw, 200, 200); 
  vertex(hw, -hh + 300, -hw, 0, 200);           
  endShape();
  
  // うなじの中心座標を画面座標(2D)に変換して保存
  // これにより「見た目通り」の当たり判定を実現
  napeScreenX = screenX(0, -hh + 150, -hw);
  napeScreenY = screenY(0, -hh + 150, -hw);
  
  // 背中（下部）
  fill(200, 150, 100); 
  beginShape(QUADS);
  vertex(hw, -hh + 300, -hw); vertex(-hw, -hh + 300, -hw); vertex(-hw, hh, -hw); vertex(hw, hh, -hw);
  endShape();
  
  // 顔（正面）
  beginShape(QUADS); texture(faceTexture);
  vertex(-hw, -hh, hw, 0, 0); vertex(hw, -hh, hw, 200, 0);
  vertex(hw, -hh + 400, hw, 200, 200); vertex(-hw, -hh + 400, hw, 0, 200); 
  endShape();
  
  // 体（正面）
  fill(200, 150, 100);
  beginShape(QUADS);
  vertex(-hw, -hh+400, hw); vertex(hw, -hh+400, hw); vertex(hw, hh, hw); vertex(-hw, hh, hw);
  endShape();
  
  // 側面
  fill(210, 160, 110); 
  beginShape(QUADS); vertex(hw, -hh, hw); vertex(hw, -hh, -hw); vertex(hw, hh, -hw); vertex(hw, hh, hw); endShape();
  beginShape(QUADS); vertex(-hw, -hh, -hw); vertex(-hw, -hh, hw); vertex(-hw, hh, hw); vertex(-hw, hh, -hw); endShape();
}

// 地面グリッドの描画
public void drawGrid() {
  // 地面（土）を描画
  noStroke();
  fill(100, 80, 50); // 茶色
  beginShape(QUADS);
  vertex(-4000, 500, -4000);
  vertex(4000, 500, -4000);
  vertex(4000, 500, 4000);
  vertex(-4000, 500, 4000);
  endShape();

  stroke(150, 130, 100); 
  strokeWeight(1);
  float groundY = 501; // 地面よりわずかに浮かせてちらつき防止
  for (int i = -4000; i < 4000; i+=400) { 
    line(i, groundY, -4000, i, groundY, 4000);
    line(-4000, groundY, i, 4000, groundY, i);
  }
  noStroke();
}

// 森の座標生成
public void createForest() {
  for(int i=0; i<50; i++) {
    float r = random(1000, 3500); 
    float theta = random(TWO_PI);
    treeX[i] = r * cos(theta);
    treeZ[i] = r * sin(theta);
    treeH[i] = random(1000, 2500);
  }
}

// 森の描画
public void drawForest() {
  fill(50, 40, 30); 
  for(int i=0; i<50; i++) {
    pushMatrix();
    translate(treeX[i], 500 - treeH[i]/2, treeZ[i]); 
    box(50, treeH[i], 50); // 幹
    translate(0, -treeH[i]/2, 0);
    fill(34, 139, 34); 
    box(200, 100, 200); // 葉
    fill(50, 40, 30); 
    popMatrix();
  }
}

// テクスチャの動的生成
public void createTextures() {
  // -------------------------------------------------
  // 顔テクスチャの生成
  // -------------------------------------------------
  faceTexture = createImage(200, 200, RGB);
  PGraphics pg = createGraphics(200, 200);
  pg.beginDraw();  
  // 肌色で塗りつぶし
  pg.background(220, 180, 140);
  pg.noStroke(); // 余計な線が入らないようにする
    // 目を描画（赤）
  pg.fill(200, 0, 0);
  pg.arc(30, 40, 40, 30, 0.5f, PI+0.5f);   // 右目
  pg.arc(70, 40, 40, 30, -0.5f, PI-0.5f);  // 左目  
  // 口を描画（白）
  pg.fill(200);
  pg.rect(25, 65, 50, 20);  // 口  
  pg.endDraw(); 
  faceTexture = pg.get();
  
  // -------------------------------------------------
  // うなじテクスチャ
  // -------------------------------------------------
  napeTexture = createImage(200, 200, RGB);
  pg = createGraphics(200, 200);
  pg.beginDraw(); 
  pg.background(220, 180, 140); 
  pg.noStroke();
  for(int i=0; i<50; i++) {
    pg.fill(150+random(100), 0, 0);
    pg.ellipse(random(200), random(200), 20 + random(20), 10 + random(10));
  }
  pg.endDraw(); 
  napeTexture = pg.get();
}

// キー入力管理
public void keyPressed() {
  if (key == 'w' || key == 'W') keyW = true;
  if (key == 'a' || key == 'A') keyA = true;
  if (key == 's' || key == 'S') keyS = true;
  if (key == 'd' || key == 'D') keyD = true;
  if (key == 'e' || key == 'E') keyE = true;
  if (key == 'q' || key == 'Q') keyQ = true;
}

public void keyReleased() {
  if (key == 'w' || key == 'W') keyW = false;
  if (key == 'a' || key == 'A') keyA = false;
  if (key == 's' || key == 'S') keyS = false;
  if (key == 'd' || key == 'D') keyD = false;
  if (key == 'e' || key == 'E') keyE = false;
  if (key == 'q' || key == 'Q') keyQ = false;
}


  public void settings() { size(800, 600, P3D); }

  static public void main(String[] passedArgs) {
    String[] appletArgs = new String[] { "AF22059_TITAN_SLAYER_3D" };
    if (passedArgs != null) {
      PApplet.main(concat(appletArgs, passedArgs));
    } else {
      PApplet.main(appletArgs);
    }
  }
}
